<?php if (isset($this->_error)) echo $this->_error;?>
<form name="publicar" method="post" action="">
	<label for="titulo">Titulo:</label>
	<input type="text" name="titulo">

	<label for="fuente">Fuente: </label>
	<input type="text" name="fuente">

	<label for="imagen"> Archivo de imagen</label>
	<input type="file" name="imagen" accept="image/jpeg,image/jpg,image/png">

	<input type="submit" name="enviar" value="Enviar">
</form>